Add signing to Windows .exe executable file (#238)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -15,7 +15,7 @@ jobs:
     if: startsWith(github.ref, 'refs/tags/')
     strategy:
       matrix:
-        os: [ubuntu-18.04, macOS-latest, windows-latest]
+        os: [ ubuntu-18.04, macOS-latest, windows-latest ]
     runs-on: ${{ matrix.os }}
     steps:
       - name: Env Variable Setup
@@ -43,7 +43,7 @@ jobs:
 
   release:
     name: Release
-    needs: [test]
+    needs: [ test ]
     if: startsWith(github.ref, 'refs/tags/')
     strategy:
       matrix:
@@ -61,13 +61,14 @@ jobs:
     steps:
       - uses: aws-actions/configure-aws-credentials@v1
         with:
+          role-skip-session-tagging: true
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-west-2
           role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
           role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
           role-duration-seconds: 1800
-          
+
       - name: Env Variable Setup
         if: matrix.os == 'windows-latest'
         run: |
@@ -87,7 +88,7 @@ jobs:
         uses: actions/checkout@v2
       - name: Package
         shell: bash
-        if: matrix.os == 'ubuntu-18.04' ||  matrix.os == 'macos-latest' 
+        if: matrix.os == 'ubuntu-18.04' ||  matrix.os == 'macos-latest'
         run: |
           name=qldb
           tag=$(git describe --tags --abbrev=0)
@@ -109,51 +110,29 @@ jobs:
       - name: MSI
         shell: powershell
         if: matrix.os == 'windows-latest'
-        run: |        
+        run: |
           $name='qldb'
           $tag=git describe --tags --abbrev=0
           $release_name="$name-$tag"
-          
+
           cargo fetch 
           cargo build --release            
-          strip "target/${{ matrix.target }}/release/${{ matrix.bin }}"
-          
-          # Install cargo-wix to compile main.wxs
-          cargo install cargo-wix
 
-          # Read the shell version from the cargo.toml file
-          $version = Get-Content .\Cargo.toml | Select-String -Pattern '^version\s*=\s*\"\d*\.\d*\.\d*'
-          
-          # Convert $version to semantic version (removing characters at the end)
-          $semantic = 'semantic' + $version.Matches[0].Value + '"'
-          
-          # Write the semantic version in the wix variable file
-          $content = '<?xml version="1.0" encoding="utf-8"?><Include><?define ' + $semantic + ' ?></Include>'
-          Set-Content -Path ./wixvariables.wxi $content
-          
-          # Create MSI based on target/wix/main.wxs
-          cargo wix --nocapture
-          
-          cd target/wix
-          mv amazon_qldb_shell*.msi ../../$release_name.msi
-        
-          cd ../../
-          $complete_file_name = $release_name + ".msi"
-          
-          # Push unsigned MSI to S3
-          $put_object_response=( aws s3api put-object --bucket ${{ secrets.AWS_UNSIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }} --body $complete_file_name --acl bucket-owner-full-control ) | ConvertFrom-Json 
+          cd target/release
+          # Push unsigned EXE to S3
+          $put_object_response=( aws s3api put-object --bucket ${{ secrets.AWS_UNSIGNED_BUCKET }} --key ${{ secrets.AWS_KEY_EXE }} --body ${{ matrix.bin }} --acl bucket-owner-full-control ) | ConvertFrom-Json
           $version_id = $put_object_response.VersionId
 
           $job_id = ""
           $num_of_retries_to_get_job_id = 3
-          
+
           # Attempt to get Job ID from bucket tagging, will retry up to 3 times before exiting with a failure code.
           # Will sleep for 5 seconds between retries.
           for (($i = 0); $i -lt $num_of_retries_to_get_job_id; $i++)
           {
-              $get_object_tagging_response=( aws s3api get-object-tagging --bucket ${{ secrets.AWS_UNSIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }} --version-id $version_id ) | ConvertFrom-Json
-              $id = $get_object_tagging_response.TagSet[0].Value       
-                
+              $get_object_tagging_response=( aws s3api get-object-tagging --bucket ${{ secrets.AWS_UNSIGNED_BUCKET }} --key ${{ secrets.AWS_KEY_EXE }} --version-id $version_id ) | ConvertFrom-Json
+              $id = $get_object_tagging_response.TagSet[0].Value
+
               if ($id)
               {
                   $job_id = $id
@@ -167,13 +146,71 @@ jobs:
              echo "Exiting because unable to retrieve job ID"
              exit 1
           }
-          
+
+          # Poll signed S3 bucket to see if the signed artifact is there
+          aws s3api wait object-exists --bucket ${{ secrets.AWS_SIGNED_BUCKET }} --key ${{ secrets.AWS_KEY_EXE }}-$job_id
+
+          # Get signed EXE from S3
+          aws s3api get-object --bucket ${{ secrets.AWS_SIGNED_BUCKET }} --key ${{ secrets.AWS_KEY_EXE }}-$job_id ${{ matrix.bin }}
+
+          cd ../../
+
+          # Install cargo-wix to compile main.wxs
+          cargo install cargo-wix
+
+          # Read the shell version from the cargo.toml file
+          $version = Get-Content .\Cargo.toml | Select-String -Pattern '^version\s*=\s*\"\d*\.\d*\.\d*'
+
+          # Convert $version to semantic version (removing characters at the end)
+          $semantic = 'semantic' + $version.Matches[0].Value + '"'
+
+          # Write the semantic version in the wix variable file
+          $content = '<?xml version="1.0" encoding="utf-8"?><Include><?define ' + $semantic + ' ?></Include>'
+          Set-Content -Path ./wixvariables.wxi $content
+
+          # Create MSI based on target/wix/main.wxs
+          cargo wix --nocapture
+
+          cd target/wix
+          mv amazon_qldb_shell*.msi ../../$release_name.msi
+
+          cd ../../
+          $complete_file_name = $release_name + ".msi"
+
+          # Push unsigned MSI to S3
+          $put_object_response=( aws s3api put-object --bucket ${{ secrets.AWS_UNSIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }} --body $complete_file_name --acl bucket-owner-full-control ) | ConvertFrom-Json 
+          $version_id = $put_object_response.VersionId
+
+          $job_id = ""
+          $num_of_retries_to_get_job_id = 3
+
+          # Attempt to get Job ID from bucket tagging, will retry up to 3 times before exiting with a failure code.
+          # Will sleep for 5 seconds between retries.
+          for (($i = 0); $i -lt $num_of_retries_to_get_job_id; $i++)
+          {
+              $get_object_tagging_response=( aws s3api get-object-tagging --bucket ${{ secrets.AWS_UNSIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }} --version-id $version_id ) | ConvertFrom-Json
+              $id = $get_object_tagging_response.TagSet[0].Value       
+
+              if ($id)
+              {
+                  $job_id = $id
+                  break
+              }
+              Start-Sleep -s 5
+          }
+
+          if ($job_id -eq "")
+          {
+             echo "Exiting because unable to retrieve job ID"
+             exit 1
+          }
+
           # Poll signed S3 bucket to see if the signed artifact is there
           aws s3api wait object-exists --bucket ${{ secrets.AWS_SIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }}-$job_id
-          
+
           # Get signed MSI from S3
           aws s3api get-object --bucket ${{ secrets.AWS_SIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }}-$job_id $complete_file_name
-          
+
       - name: Publish
         uses: softprops/action-gh-release@v1
         with:
